name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter

  flutter_gpu:
    sdk: flutter
    
  gpu_vector_tile_renderer:
    path: ..

  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/compiled_style/
